#!/usr/bin/env bash
# Extract scroll-scrub frame sequences from the three Seal Point clips.
# Usage: ./extract-frames.sh clip1.mp4 clip2.mp4 clip3.mp4
# Output: site/assets/frames/clipN/f_%04d.webp at 12fps, 1920px wide, q80
set -euo pipefail

FF="/c/Users/User/AppData/Local/Microsoft/WinGet/Packages/Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe/ffmpeg-8.1.1-full_build/bin/ffmpeg.exe"
SITE="$(cd "$(dirname "$0")/../site" && pwd)"
FPS=12

for n in 1 2 3; do
  src="${!n}"
  out="$SITE/assets/frames/clip$n"
  rm -f "$out"/f_*.webp
  "$FF" -y -v error -i "$src" \
    -vf "fps=$FPS,scale=1920:-2:flags=lanczos" \
    -c:v libwebp -quality 80 "$out/f_%04d.webp"
  count=$(ls "$out" | wc -l | tr -d ' ')
  echo "clip$n: $count frames"
done

# Regenerate the manifest with real counts
c1=$(ls "$SITE/assets/frames/clip1" | wc -l | tr -d ' ')
c2=$(ls "$SITE/assets/frames/clip2" | wc -l | tr -d ' ')
c3=$(ls "$SITE/assets/frames/clip3" | wc -l | tr -d ' ')
cat > "$SITE/js/manifest.js" << EOF
// Frame sequence manifest — regenerated by the extraction pipeline.
window.SEQUENCE = {
  ext: 'webp',
  frameW: 1920,
  frameH: 1080,
  clips: [
    { dir: 'assets/frames/clip1', count: $c1 },
    { dir: 'assets/frames/clip2', count: $c2 },
    { dir: 'assets/frames/clip3', count: $c3 }
  ]
};
EOF
echo "manifest updated: $c1 / $c2 / $c3"
